name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Black (auto formatting)
      run: black .

    - name: Run Flake8 (linting)
      run: flake8 .


    - name: Run tests
      run: |
        export PYTHONPATH=$PYTHONPATH:$(pwd)
        pytest app/tests

    - name: Deploy to Render
      run: |
        curl -X POST \
        -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
        -H "Accept: application/json" \
        https://liteparse-resume-parser.onrender.com
        
